language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
script: ./gradlew build --continue
notifications:
  email:
    recipients: paul.t.oconnell@gmail.com