# https://lkrnac.net/blog/2016/02/speed-gradle-build-travisci/
# https://github.com/lkrnac/blog-2016-01-selenium-on-travis/blob/master/.travis.yml
language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
script: ./gradlew build --continue
notifications:
  email:
    recipients: paul.t.oconnell@gmail.com